// apps/looplicant/src/import/ui/SkillModalContent.tsx
import { Skill, Experience } from "@lct/looplicant-types";
import { useMemo } from "react";

export default function SkillModalContent({
  skill,
  experience,
}: {
  skill: Skill;
  experience: Experience[];
}) {
  const skillWithExperience = useMemo(() => {
    return {
      ...skill,
      sources: skill.sources.map((src) => ({
        ...src,
        experience: experience.find((exp) => exp.id === src.experienceId),
      })),
    };
  }, [skill, experience]);

  return (
    <div className="space-y-2 max-w-24 min-w-xs">
      <p className="text-xs text-gray-500 italic">{skill.category}</p>
      <p className="text-sm text-gray-700">{skill.description}</p>
      <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
        <div
          className="h-full bg-accent"
          style={{ width: `${skill.level}%` }}
        />
      </div>
      <div className="text-xs text-gray-500">
        <p className="mt-4 mb-2">See experience:</p>
        <ul className="list-disc list-inside">
          {skillWithExperience.sources.map((src) => (
            <li key={src.experienceId} className="truncate">
              <a href={`#${src.experienceId}`}>
                {src.experience?.title} - {src.experience?.company}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

// packages/ui/src/lib/skill/SkillModalContent.svelte
<script lang="ts">
  import type { Skill, Experience } from "@lct/looplicant-types";

  type Props = {
    skill: Skill;
    experience: Experience[];
    host: HTMLElement;
  };

  let { skill, experience, host }: Props = $props();

  // derived skill with matching experience references
  const skillWithExperience = $derived.by(() => ({
    ...skill,
    sources: skill.sources.map((src) => ({
      ...src,
      experience: experience.find((exp) => exp.id === src.experienceId),
    })),
  }));

  function scrollToExperience(evt: MouseEvent, expId: string) {
    const expHeader = host.shadowRoot?.getElementById(expId);
    expHeader?.scrollIntoView();
  }
</script>

<div class="space-y-2 max-w-24 min-w-xs">
  <p class="text-xs text-gray-500 italic mb-1">{skill.category}</p>
  <p class="text-sm text-gray-700">{skill.description}</p>

  <div class="h-2 bg-gray-200 rounded-full overflow-hidden">
    <div class="h-full bg-accent" style={`width: ${skill.level}%`}></div>
  </div>

  <div class="text-xs text-gray-500">
    <p class="mt-4 mb-2">See experience:</p>
    <ul class="list-disc list-inside">
      {#each skillWithExperience.sources as src (src.experienceId)}
        <li class="">
          <button
            type="button"
            class="truncate"
            onmousedown={(evt) => scrollToExperience(evt, src.experienceId)}
            style="max-width: 22em"
          >
            {src.experience?.title} - {src.experience?.company}
          </button>
        </li>
      {/each}
    </ul>
  </div>
</div>
