// src/import/ui/SkillModal.tsx
import { Modal } from "@/components/ui/Modal";
import SkillModalContent from "./SkillModalContent";
import { SkillNode } from "../lib/map-helper";
import { Experience } from "../lib/actions";

export type SkillModalData = {
  x: number;
  y: number;
  data: SkillNode;
};

export default function SkillModal({
  skillModalData,
  experience,
  handleClose,
}: {
  skillModalData?: SkillModalData;
  experience?: Experience[];
  handleClose: () => void;
}) {
  return (
    <>
      {skillModalData && (
        <Modal
          isOpen={!!skillModalData}
          onClose={handleClose}
          x={skillModalData.x}
          y={skillModalData.y}
          title={skillModalData.data.title}
        >
          {skillModalData?.data.skill && experience && (
            <SkillModalContent
              skill={skillModalData.data.skill}
              experience={experience}
            />
          )}
        </Modal>
      )}
    </>
  );
}

// packages/ui/src/lib/skill/SkillModal.svelte
<script lang="ts">
  import Modal from "../modal/Modal.svelte";
  import type { SkillNode } from "./map-helper";
  import SkillModalContent from "./SkillModalContent.svelte";
  import type { Experience } from "@lct/looplicant-types";

  export type SkillModalData = {
    x: number;
    y: number;
    data: SkillNode;
  };

  type Props = {
    skillModalData?: SkillModalData;
    experience?: Experience[];
    host: HTMLElement;
    handleClose: () => void;
  };

  let { skillModalData, experience, host, handleClose }: Props = $props();
</script>

{#if skillModalData}
  <Modal
    isOpen
    onClose={handleClose}
    x={skillModalData.x}
    y={skillModalData.y}
    title={skillModalData.data.title}
  >
    {#if skillModalData.data.skill && experience}
      <SkillModalContent
        skill={skillModalData.data.skill}
        {experience}
        {host}
      />
    {/if}
  </Modal>
{/if}
