// src/components/ui/CardLoader.tsx
import { Loader2, LucideIcon } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "./Card";
import { cn } from "@/lib/utils";

export default function CardLoader({
  loadingTitle,
  title,
  isLoading,
  children,
  icon: Icon,
}: {
  loadingTitle: string;
  title: string;
  isLoading: boolean;
  children: React.ReactNode;
  icon: LucideIcon;
}) {
  return (
    <Card className={cn({ "animate-pulse": isLoading })}>
      <CardHeader>
        <div className="flex items-center space-x-3">
          {isLoading ? (
            <Loader2 className="h-7 w-7 text-muted-foreground" />
          ) : (
            <Icon className="h-7 w-7 text-primary" />
          )}
          <CardTitle className="text-muted-foreground">
            {isLoading ? loadingTitle : title}
          </CardTitle>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {isLoading ? (
          <>
            <div className="h-5 bg-background rounded w-3/4"></div>
            <div className="h-5 bg-background rounded w-full"></div>
            <div className="h-5 bg-background rounded w-5/6"></div>
            <div className="h-5 bg-background rounded w-full"></div>
          </>
        ) : (
          <>{children}</>
        )}
      </CardContent>
    </Card>
  );
}

// packages/ui/src/lib/card/CardLoader.svelte
<script lang="ts">
  import { Loader2 } from "lucide-svelte";
  import Card from "./Card.svelte";
  import CardHeader from "./CardHeader.svelte";
  import CardTitle from "./CardTitle.svelte";
  import CardContent from "./CardContent.svelte";
  import type { Snippet } from "svelte";
  import type { ClassValue } from "svelte/elements";

  interface Props {
    class?: ClassValue;
    loadingTitle: string;
    title: string;
    isLoading: boolean;
    icon: typeof Loader2;
    children: Snippet;
  }

  let props: Props = $props();
</script>

<Card class={[{ "animate-pulse": props.isLoading }, props.class]}>
  {#snippet header()}
    <CardHeader>
      <div class="flex items-center">
        {#if props.isLoading}
          <Loader2 class="h-7 w-7 text-muted-foreground" />
        {:else}
          <svelte:component this={props.icon} class="h-7 w-7 text-primary" />
        {/if}
        <CardTitle class="text-muted-foreground ml-2">
          {props.isLoading ? props.loadingTitle : props.title}
        </CardTitle>
      </div>
    </CardHeader>
  {/snippet}

  {#snippet content()}
    <CardContent class="space-y-4">
      {#if props.isLoading}
        <div class="h-5 bg-background rounded w-3/4"></div>
        <div class="h-5 bg-background rounded w-full"></div>
        <div class="h-5 bg-background rounded w-5/6"></div>
        <div class="h-5 bg-background rounded w-full"></div>
      {:else}
        {@render props.children?.()}
      {/if}
    </CardContent>
  {/snippet}
</Card>
